### ISSUE TITLE
Port to new OS/build from source

### ISSUE THREAD

**Issue by bil-ash** [raub/node-3d-ready#10]
I would like to port this library to android using [nodejs-mobile(cordova)](https://github.com/janeasystems/nodejs-mobile-cordova#native-modules) . But none of the n-api libraries on which this library is dependent -like https://github.com/node-3d/deps-opengl-raub provide instructions for building from source, all download prebuilt libraries. The best thing would be if you yourself port the library to android. If you are not interested in doing so, please provide the docs for building the necessary native libraries from source.

**Comment by raub** [comment]
Hello. `deps-opengl-raub` is distributing the binaries for GLFW, GLEW, along with platform GL and possibly other libs. For Windows, I took all the binaries as-is from the official web-sites. For Linux, I downloaded some of those as binaries, from https://packages.ubuntu.com.

What I have built is GLEW and GLFW for OSX and Linux. As I don't have OSX device and don't use the Linux VM much, I built them with Travis CI: https://github.com/node-3d/deps-opengl-raub/blob/master/.travis.yml. Here are the commands I used for Linux:

```
sudo apt-get update -qq
sudo apt-get install -qq xorg-dev
chmod +x src/linux-glfw.sh && src/linux-glfw.sh
```

And `src/linux-glfw.sh` is unzipping the GLFW sources (taken from official releases page https://github.com/glfw/glfw/releases), and running `cmake`.

---

That said, I also use https://github.com/node-3d/addon-tools-raub. It provides integration-level assistance. You can see it used in `index.js` - `module.exports = require('addon-tools-raub').paths(__dirname);`. And as per README.md https://github.com/node-3d/deps-opengl-raub#example-bindinggyp it is also used to obtain the directory path to libraries and headers.

Basically, if you want to use it with minimal changes, you will have to add an addtional platform to the supported list. Just next to `windows, linux, osx` - `android`, in https://github.com/node-3d/addon-tools-raub/blob/master/index.js. And pack the Android binaries to `bin-android` when you have them.

---

Everything above applies to https://github.com/node-3d/deps-freeimage-raub - if the native libraries somehow work on Android, it will be possible. But I've never tried to build anything for Android and don't even know where do people start with that. Feel free to ask any additional questions, I'll be glad to help you bilding it on Android. I do have Android Studio installed if it helps, may be I might also try to build something with it (but I don't know how, as I only used it for emulator).

**Comment by raub** [comment]
@bil-ash by the way, do you have any example of a similar node addon, that would run on Android (and what exactly does it mean to run it on Android)? if I understand how it works, may be I can try to port the library

**Comment by bil-ash** [comment]
Around 2 years ago I managed to compile and run leveldown for android. Configuring the NDK was bit messy,most probably because of using on Windows Subsystem for Linux(I don't have an actual linux PC). Tonight(its morning at my place right now) I will see if I can reproduce the same with current version and let you know tonight or tomorrow.

**Comment by raub** [comment]
@bil-ash
Yeah, I hope it didn't blow up, and you are still OK. I was just thinking why do you need this on Android at all? You see, the point of this library is that Cromium (and other guys) do have WebGL, but they spoof the real GL resource IDs. Even if they implement WebGL with GL anyway. While Angle WebGL implementation is actually DirectX.

And all of that nonsense won't let you make any GL resource interoperation. Like shared GL context (with other DLLs), OpenCL interop, and CUDA interop. It has all started here: https://store.steampowered.com/sub/412112 - this is a GPU intensive game. And it would be impossible to visualize that amount of data, if it required sending the data-copy through CPU each frame. The only solution is using a GL resource interop, and work on-GPU the whole time without CPU being involved.

The GL context sharing thing is also used there to connect with a QML rendering engine. So that we can display QML-driven UI on the screen. While QML needs its own context with some specific settings, they still share the textures with the main context. And we can display that UI-texture as an overlay in 3D scene.

Hence I'm asking, why do you need it on Android in the first place?

**Comment by bil-ash** [comment]
The WebGL implementation in Android is dependent on webview version and their are differences(quirks) between some versions. So I was thinking of using this library . But I couldn't even try building as I did not have NDK. Now I plan to use https://mozilla.github.io/geckoview/ for consistency. Thanks for the the interest.
AS the issue is resolved for me,so closing it.
