### ISSUE TITLE
Is this library cross compatible with browsers?

### ISSUE THREAD

**Issue by tylers-username** [raub/node-3d-ready#6]
Is this library built with only desktop in mind or, given its WebGL support, are modern browsers supported as well?

**Comment by raub** [comment]
Hello. In short, this is a desktop library.

This library is designed to create a **browserlike** environment for Node.js apps. It consists of Canvas emulation, minor DOM emulation, Image library, WebGL emulation, builtin three.js and a window control system. All of those you either already have in the browser or can obtain (three.js) without additional effort.

There are also plugins to this library. Since they are based on binary addons (dll/so), you can't use them in a browser. Examples are:

- QML - not needed in a browser, I guess.
- Bullet based physics - Bullet itself is available as ammo.js for browsers.
- WebAudio - exists in a browser.

Coming soon:

- CUDA - impossible in a browser.
- OpenCL - could be WebCL, though never happenned.

**Comment by tylers-username** [comment]
Thank you for the detailed answer. I've been in search of a library that allows NodeJS to work with OpenGL and thought it would be interesting if the JS that drove OpenGL could be recycled in the browser.

Thanks again for such a detailed answer for what was probably silly question.

**Comment by raub** [comment]
@tylerssn Just to clarify, you seem to have found such a library here. The API is highly compatible with WebGL, hence the code can be reused in both directions: Node <-> Browser.

See the example:
Live three.js demo [here](https://threejs.org/examples/?q=geometr#webgl_geometry_cube), the original JS code can be found [here](https://github.com/mrdoob/three.js/blob/master/examples/webgl_geometry_cube.html). And that [code with minimal changes](https://github.com/node-3d/3d-core-raub/blob/master/examples/three/crate.js) can draw the same thing in Node3D.

More complex examples work as well: [original](https://threejs.org/examples/?q=post#webgl_postprocessing_advanced) vs [Node3D](https://github.com/node-3d/3d-core-raub/blob/master/examples/three/post.js).

Three.js is not the only way Node3D works, you can use the raw WebGL or other browser libs.
